export const rawData = [
  {
    id: 1,
    year: 2018,
    month: "Grudzien", //rather universal date, Java / JavaScript format that it could be translated
    income: 271,
    rent: 1100,
    food: 371.7,
    cleaningSupplies: 30,
    phone: 25,
    transport: 35.1,
    education: 0,
    traveling: 299,
    travelingEquipment: 0,
    restaurants: 48,
    beauty: 0,
    clothes: 0,
    entertainment: 0,
    presents: 345,
    electronics: 0,
    fines: 0,
    others: 0,
    totalExpenses: 2253.6
  },
  {
    id: 2,
    year: 2019,
    month: "Styczen", //rather universal date, Java / JavaScript format that it could be translated
    income: 494,
    rent: 1100,
    food: 245.54,
    cleaningSupplies: 15,
    phone: 35,
    transport: 24.9,
    education: 260,
    traveling: 64,
    travelingEquipment: 0,
    restaurants: 46.5,
    beauty: 20,
    clothes: 0,
    entertainment: 170,
    presents: 60,
    electronics: 0,
    fines: 1.3,
    others: 85,
    totalExpenses: 2127.24
  },
  {
    id: 3,
    year: 2019,
    month: "Luty", //rather universal date, Java / JavaScript format that it could be translated
    income: 740.65,
    rent: 1100,
    food: 338.38,
    cleaningSupplies: 5,
    phone: 25,
    transport: 354.07,
    education: 0,
    traveling: 0,
    travelingEquipment: 0,
    restaurants: 13.9,
    beauty: 270,
    clothes: 235.88,
    entertainment: 0,
    presents: 0,
    electronics: 0,
    fines: 0,
    others: 0,
    totalExpenses: 2437.23
  },
  {
    id: 4,
    year: 2019,
    month: "March", //rather universal date, Java / JavaScript format that it could be translated
    income: 0,
    rent: 1100,
    food: 209.33,
    cleaningSupplies: 0,
    phone: 25,
    transport: 139.27,
    education: 0,
    traveling: 0,
    travelingEquipment: 0,
    restaurants: 32,
    beauty: 0,
    clothes: 0,
    entertainment: 0,
    presents: 0,
    electronics: 0,
    fines: 0,
    others: 10,
    totalExpenses: 1515.6
  },
  {
    id: 1,
    year: 2018,
    month: "Grudzien", //rather universal date, Java / JavaScript format that it could be translated
    income: 271,
    rent: 1100,
    food: 371.7,
    cleaningSupplies: 30,
    phone: 25,
    transport: 35.1,
    education: 0,
    traveling: 299,
    travelingEquipment: 0,
    restaurants: 48,
    beauty: 0,
    clothes: 0,
    entertainment: 0,
    presents: 345,
    electronics: 0,
    fines: 0,
    others: 0,
    totalExpenses: 2253.6
  },
  {
    id: 2,
    year: 2019,
    month: "Styczen", //rather universal date, Java / JavaScript format that it could be translated
    income: 494,
    rent: 1100,
    food: 245.54,
    cleaningSupplies: 15,
    phone: 35,
    transport: 24.9,
    education: 260,
    traveling: 64,
    travelingEquipment: 0,
    restaurants: 46.5,
    beauty: 20,
    clothes: 0,
    entertainment: 170,
    presents: 60,
    electronics: 0,
    fines: 1.3,
    others: 85,
    totalExpenses: 2127.24
  },
  {
    id: 3,
    year: 2019,
    month: "Luty", //rather universal date, Java / JavaScript format that it could be translated
    income: 740.65,
    rent: 1100,
    food: 338.38,
    cleaningSupplies: 5,
    phone: 25,
    transport: 354.07,
    education: 0,
    traveling: 0,
    travelingEquipment: 0,
    restaurants: 13.9,
    beauty: 270,
    clothes: 235.88,
    entertainment: 0,
    presents: 0,
    electronics: 0,
    fines: 0,
    others: 0,
    totalExpenses: 2437.23
  },
  {
    id: 4,
    year: 2019,
    month: "March", //rather universal date, Java / JavaScript format that it could be translated
    income: 0,
    rent: 1100,
    food: 209.33,
    cleaningSupplies: 0,
    phone: 25,
    transport: 139.27,
    education: 0,
    traveling: 0,
    travelingEquipment: 0,
    restaurants: 32,
    beauty: 0,
    clothes: 0,
    entertainment: 0,
    presents: 0,
    electronics: 0,
    fines: 0,
    others: 10,
    totalExpenses: 1515.6
  },
  {
    id: 1,
    year: 2018,
    month: "Grudzien", //rather universal date, Java / JavaScript format that it could be translated
    income: 271,
    rent: 1100,
    food: 371.7,
    cleaningSupplies: 30,
    phone: 25,
    transport: 35.1,
    education: 0,
    traveling: 299,
    travelingEquipment: 0,
    restaurants: 48,
    beauty: 0,
    clothes: 0,
    entertainment: 0,
    presents: 345,
    electronics: 0,
    fines: 0,
    others: 0,
    totalExpenses: 2253.6
  },
  {
    id: 2,
    year: 2019,
    month: "Styczen", //rather universal date, Java / JavaScript format that it could be translated
    income: 494,
    rent: 1100,
    food: 245.54,
    cleaningSupplies: 15,
    phone: 35,
    transport: 24.9,
    education: 260,
    traveling: 64,
    travelingEquipment: 0,
    restaurants: 46.5,
    beauty: 20,
    clothes: 0,
    entertainment: 170,
    presents: 60,
    electronics: 0,
    fines: 1.3,
    others: 85,
    totalExpenses: 2127.24
  },
  {
    id: 3,
    year: 2019,
    month: "Luty", //rather universal date, Java / JavaScript format that it could be translated
    income: 740.65,
    rent: 1100,
    food: 338.38,
    cleaningSupplies: 5,
    phone: 25,
    transport: 354.07,
    education: 0,
    traveling: 0,
    travelingEquipment: 0,
    restaurants: 13.9,
    beauty: 270,
    clothes: 235.88,
    entertainment: 0,
    presents: 0,
    electronics: 0,
    fines: 0,
    others: 0,
    totalExpenses: 2437.23
  },
  {
    id: 4,
    year: 2019,
    month: "March", //rather universal date, Java / JavaScript format that it could be translated
    income: 0,
    rent: 900,
    food: 209.33,
    cleaningSupplies: 0,
    phone: 25,
    transport: 139.27,
    education: 0,
    traveling: 0,
    travelingEquipment: 0,
    restaurants: 32,
    beauty: 0,
    clothes: 0,
    entertainment: 0,
    presents: 0,
    electronics: 0,
    fines: 0,
    others: 10,
    totalExpenses: 1515.6
  }
];
